# Generated by Django 3.1.7 on 2021-02-26 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20210224_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Export', to='artists.artist')),
            ],
        ),
    ]
