# Generated by Django 3.1.7 on 2021-02-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_export'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Export',
        ),
    ]
